//tests were automatically generated by claude hahaha
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <cuda_runtime.h>
#include "../cuda/cuda_backend.h"
#include "../cuda/cuda_mem.h"
#include "../cuda/kernels/elementwise.cuh"
#include "../cuda/kernels/reduce.cuh"
#include "../cuda/kernels/matmul.cuh"
#include "../cuda/kernels/batchnorm.cuh"
#include "../cuda/kernels/conv2d.cuh"

/* ------------------------------------------------------------------ */
/*  Minimal test harness                                              */
/* ------------------------------------------------------------------ */

static int g_passed = 0;
static int g_failed = 0;

#define ASSERT_TRUE(expr, msg)                                         \
    do {                                                               \
        if (expr) { printf("  [PASS] %s\n", msg); g_passed++; }       \
        else      { printf("  [FAIL] %s\n", msg); g_failed++; }       \
    } while (0)

#define ASSERT_NEAR(actual, expected, tol, msg)                        \
    do {                                                               \
        float _a = (actual), _e = (expected);                          \
        if (fabsf(_a - _e) <= (tol)) {                                \
            printf("  [PASS] %s\n", msg);                              \
            g_passed++;                                                \
        } else {                                                       \
            printf("  [FAIL] %s  (expected %.6f, got %.6f)\n",         \
                   msg, (double)_e, (double)_a);                       \
            g_failed++;                                                \
        }                                                              \
    } while (0)

#define EPS 1e-4f

/* helper: upload host array, run on GPU, download result */
static void upload(float* d_dst, const float* h_src, int n) {
    cuda_copy_to_device(d_dst, h_src, n);
}
static void download(float* h_dst, const float* d_src, int n) {
    cuda_copy_to_host(h_dst, d_src, n);
    cudaDeviceSynchronize();
}

/* ================================================================== */
/*  ELEMENTWISE TESTS                                                 */
/* ================================================================== */

static void test_add(void) {
    printf("\n--- test_add ---\n");
    float a[] = {1.0f, 2.0f, 3.0f, 4.0f};
    float b[] = {10.0f, 20.0f, 30.0f, 40.0f};
    float out[4];
    int n = 4;

    float *d_a = cuda_malloc_float(n);
    float *d_b = cuda_malloc_float(n);
    float *d_o = cuda_malloc_float(n);
    upload(d_a, a, n); upload(d_b, b, n);

    cuda_add(d_a, d_b, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0], 11.0f, EPS, "1 + 10 == 11");
    ASSERT_NEAR(out[1], 22.0f, EPS, "2 + 20 == 22");
    ASSERT_NEAR(out[2], 33.0f, EPS, "3 + 30 == 33");
    ASSERT_NEAR(out[3], 44.0f, EPS, "4 + 40 == 44");

    cuda_free(d_a); cuda_free(d_b); cuda_free(d_o);
}

static void test_sub(void) {
    printf("\n--- test_sub ---\n");
    float a[] = {10.0f, 20.0f, 5.0f};
    float b[] = {3.0f,  25.0f, 5.0f};
    float out[3];
    int n = 3;

    float *d_a = cuda_malloc_float(n), *d_b = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n); upload(d_b, b, n);

    cuda_sub(d_a, d_b, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0],  7.0f, EPS, "10 - 3 == 7");
    ASSERT_NEAR(out[1], -5.0f, EPS, "20 - 25 == -5");
    ASSERT_NEAR(out[2],  0.0f, EPS, "5 - 5 == 0");

    cuda_free(d_a); cuda_free(d_b); cuda_free(d_o);
}

static void test_mul(void) {
    printf("\n--- test_mul (hadamard) ---\n");
    float a[] = {2.0f, 3.0f, -1.0f, 0.0f};
    float b[] = {5.0f, 4.0f,  7.0f, 99.0f};
    float out[4];
    int n = 4;

    float *d_a = cuda_malloc_float(n), *d_b = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n); upload(d_b, b, n);

    cuda_mul(d_a, d_b, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0], 10.0f, EPS, "2 * 5 == 10");
    ASSERT_NEAR(out[1], 12.0f, EPS, "3 * 4 == 12");
    ASSERT_NEAR(out[2], -7.0f, EPS, "-1 * 7 == -7");
    ASSERT_NEAR(out[3],  0.0f, EPS, "0 * 99 == 0");

    cuda_free(d_a); cuda_free(d_b); cuda_free(d_o);
}

static void test_scale(void) {
    printf("\n--- test_scale ---\n");
    float a[] = {1.0f, 2.0f, -3.0f};
    float scalar = 0.5f;
    float out[3];
    int n = 3;

    float *d_a = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n);

    cuda_scale(d_a, scalar, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0],  0.5f,  EPS, "1.0 * 0.5 == 0.5");
    ASSERT_NEAR(out[1],  1.0f,  EPS, "2.0 * 0.5 == 1.0");
    ASSERT_NEAR(out[2], -1.5f,  EPS, "-3.0 * 0.5 == -1.5");

    cuda_free(d_a); cuda_free(d_o);
}

/* ================================================================== */
/*  ACTIVATION FORWARD TESTS                                          */
/* ================================================================== */

static void test_relu_forward(void) {
    printf("\n--- test_relu_forward ---\n");
    float a[] = {-2.0f, 0.0f, 3.0f, -0.5f};
    float out[4];
    int n = 4;

    float *d_a = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n);

    cuda_relu_forward(d_a, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0], 0.0f, EPS, "relu(-2) == 0");
    ASSERT_NEAR(out[1], 0.0f, EPS, "relu(0) == 0");
    ASSERT_NEAR(out[2], 3.0f, EPS, "relu(3) == 3");
    ASSERT_NEAR(out[3], 0.0f, EPS, "relu(-0.5) == 0");

    cuda_free(d_a); cuda_free(d_o);
}

static void test_sigmoid_forward(void) {
    printf("\n--- test_sigmoid_forward ---\n");
    float a[] = {0.0f, 1000.0f, -1000.0f};
    float out[3];
    int n = 3;

    float *d_a = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n);

    cuda_sigmoid_forward(d_a, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0], 0.5f, EPS, "sigmoid(0) == 0.5");
    ASSERT_NEAR(out[1], 1.0f, EPS, "sigmoid(large) == 1.0");
    ASSERT_NEAR(out[2], 0.0f, EPS, "sigmoid(-large) == 0.0");

    cuda_free(d_a); cuda_free(d_o);
}

static void test_tanh_forward(void) {
    printf("\n--- test_tanh_forward ---\n");
    float a[] = {0.0f, 100.0f, -100.0f};
    float out[3];
    int n = 3;

    float *d_a = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_a, a, n);

    cuda_tanh_forward(d_a, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0],  0.0f, EPS, "tanh(0) == 0");
    ASSERT_NEAR(out[1],  1.0f, EPS, "tanh(large) == 1");
    ASSERT_NEAR(out[2], -1.0f, EPS, "tanh(-large) == -1");

    cuda_free(d_a); cuda_free(d_o);
}

/* ================================================================== */
/*  ACTIVATION BACKWARD TESTS                                        */
/* ================================================================== */

static void test_relu_backward(void) {
    printf("\n--- test_relu_backward ---\n");
    //  z (pre-activation):  positive -> gradient passes, negative -> gradient dies
    float z[]  = {2.0f, -1.0f, 0.5f, -3.0f};
    float dA[] = {1.0f,  1.0f, 1.0f,  1.0f};
    float out[4];
    int n = 4;

    float *d_z = cuda_malloc_float(n), *d_dA = cuda_malloc_float(n), *d_o = cuda_malloc_float(n);
    upload(d_z, z, n); upload(d_dA, dA, n);

    cuda_relu_backward(d_z, d_dA, d_o, n);
    download(out, d_o, n);

    ASSERT_NEAR(out[0], 1.0f, EPS, "relu_back(z=2, dA=1) == 1  (active)");
    ASSERT_NEAR(out[1], 0.0f, EPS, "relu_back(z=-1, dA=1) == 0 (dead)");
    ASSERT_NEAR(out[2], 1.0f, EPS, "relu_back(z=0.5, dA=1) == 1 (active)");
    ASSERT_NEAR(out[3], 0.0f, EPS, "relu_back(z=-3, dA=1) == 0 (dead)");

    cuda_free(d_z); cuda_free(d_dA); cuda_free(d_o);
}

static void test_sigmoid_backward(void) {
    printf("\n--- test_sigmoid_backward ---\n");
    // sigmoid'(0) = sigmoid(0) * (1 - sigmoid(0)) = 0.5 * 0.5 = 0.25
    float z[]  = {0.0f};
    float dA[] = {1.0f};
    float out[1];

    float *d_z = cuda_malloc_float(1), *d_dA = cuda_malloc_float(1), *d_o = cuda_malloc_float(1);
    upload(d_z, z, 1); upload(d_dA, dA, 1);

    cuda_sigmoid_backward(d_z, d_dA, d_o, 1);
    download(out, d_o, 1);

    ASSERT_NEAR(out[0], 0.25f, EPS, "sigmoid_back(z=0, dA=1) == 0.25");

    cuda_free(d_z); cuda_free(d_dA); cuda_free(d_o);
}

static void test_tanh_backward(void) {
    printf("\n--- test_tanh_backward ---\n");
    // tanh'(0) = 1 - tanh(0)^2 = 1 - 0 = 1
    float z[]  = {0.0f};
    float dA[] = {1.0f};
    float out[1];

    float *d_z = cuda_malloc_float(1), *d_dA = cuda_malloc_float(1), *d_o = cuda_malloc_float(1);
    upload(d_z, z, 1); upload(d_dA, dA, 1);

    cuda_tanh_backward(d_z, d_dA, d_o, 1);
    download(out, d_o, 1);

    ASSERT_NEAR(out[0], 1.0f, EPS, "tanh_back(z=0, dA=1) == 1.0");

    cuda_free(d_z); cuda_free(d_dA); cuda_free(d_o);
}

static void test_sigmoid_backward_scales_by_dA(void) {
    printf("\n--- test_sigmoid_backward_scales_by_dA ---\n");
    // dZ = dA * sigmoid'(z).  With dA=2, z=0: dZ = 2 * 0.25 = 0.5
    float z[]  = {0.0f};
    float dA[] = {2.0f};
    float out[1];

    float *d_z = cuda_malloc_float(1), *d_dA = cuda_malloc_float(1), *d_o = cuda_malloc_float(1);
    upload(d_z, z, 1); upload(d_dA, dA, 1);

    cuda_sigmoid_backward(d_z, d_dA, d_o, 1);
    download(out, d_o, 1);

    ASSERT_NEAR(out[0], 0.5f, EPS, "sigmoid_back(z=0, dA=2) == 0.5");

    cuda_free(d_z); cuda_free(d_dA); cuda_free(d_o);
}

/* ================================================================== */
/*  REDUCE TESTS                                                      */
/* ================================================================== */

static void test_sum_rows(void) {
    printf("\n--- test_sum_rows ---\n");
    // 2x3 matrix (row-major):
    //   [1 2 3]   -> row sum = 6
    //   [4 5 6]   -> row sum = 15
    float in[] = {1, 2, 3, 4, 5, 6};
    float out[2];
    int rows = 2, cols = 3;

    float *d_in = cuda_malloc_float(6), *d_out = cuda_malloc_float(2);
    upload(d_in, in, 6);

    cuda_sum_rows(d_in, d_out, rows, cols);
    download(out, d_out, 2);

    ASSERT_NEAR(out[0],  6.0f, EPS, "row 0 sum: 1+2+3 == 6");
    ASSERT_NEAR(out[1], 15.0f, EPS, "row 1 sum: 4+5+6 == 15");

    cuda_free(d_in); cuda_free(d_out);
}

static void test_sum_cols(void) {
    printf("\n--- test_sum_cols ---\n");
    // 2x3 matrix:
    //   [1 2 3]
    //   [4 5 6]
    //   col sums = [5, 7, 9]
    float in[] = {1, 2, 3, 4, 5, 6};
    float out[3];
    int rows = 2, cols = 3;

    float *d_in = cuda_malloc_float(6), *d_out = cuda_malloc_float(3);
    upload(d_in, in, 6);

    cuda_sum_cols(d_in, d_out, rows, cols);
    download(out, d_out, 3);

    ASSERT_NEAR(out[0], 5.0f, EPS, "col 0 sum: 1+4 == 5");
    ASSERT_NEAR(out[1], 7.0f, EPS, "col 1 sum: 2+5 == 7");
    ASSERT_NEAR(out[2], 9.0f, EPS, "col 2 sum: 3+6 == 9");

    cuda_free(d_in); cuda_free(d_out);
}

static void test_sum_rows_single_row(void) {
    printf("\n--- test_sum_rows_single_row ---\n");
    float in[] = {2, 4, 6};
    float out[1];

    float *d_in = cuda_malloc_float(3), *d_out = cuda_malloc_float(1);
    upload(d_in, in, 3);

    cuda_sum_rows(d_in, d_out, 1, 3);
    download(out, d_out, 1);

    ASSERT_NEAR(out[0], 12.0f, EPS, "single row sum: 2+4+6 == 12");

    cuda_free(d_in); cuda_free(d_out);
}

/* ================================================================== */
/*  MATMUL TESTS                                                      */
/* ================================================================== */

static void test_matmul_identity(void) {
    printf("\n--- test_matmul_identity ---\n");
    // [1 2] * [1 0] = [1 2]
    // [3 4]   [0 1]   [3 4]
    float A[] = {1, 2, 3, 4};
    float I[] = {1, 0, 0, 1};
    float C[4];

    float *d_A = cuda_malloc_float(4), *d_I = cuda_malloc_float(4), *d_C = cuda_malloc_float(4);
    upload(d_A, A, 4); upload(d_I, I, 4);

    cuda_matmul(d_A, d_I, d_C, 2, 2, 2);
    download(C, d_C, 4);

    ASSERT_NEAR(C[0], 1.0f, EPS, "A*I [0,0] == 1");
    ASSERT_NEAR(C[1], 2.0f, EPS, "A*I [0,1] == 2");
    ASSERT_NEAR(C[2], 3.0f, EPS, "A*I [1,0] == 3");
    ASSERT_NEAR(C[3], 4.0f, EPS, "A*I [1,1] == 4");

    cuda_free(d_A); cuda_free(d_I); cuda_free(d_C);
}

static void test_matmul_2x3_times_3x2(void) {
    printf("\n--- test_matmul_2x3_times_3x2 ---\n");
    // A(2x3) = [1 2 3]    B(3x2) = [7  8]
    //          [4 5 6]              [9 10]
    //                               [11 12]
    // C = A*B = [1*7+2*9+3*11  1*8+2*10+3*12] = [58  64]
    //           [4*7+5*9+6*11  4*8+5*10+6*12]   [139 154]
    float A[] = {1, 2, 3, 4, 5, 6};
    float B[] = {7, 8, 9, 10, 11, 12};
    float C[4];

    float *d_A = cuda_malloc_float(6), *d_B = cuda_malloc_float(6), *d_C = cuda_malloc_float(4);
    upload(d_A, A, 6); upload(d_B, B, 6);

    cuda_matmul(d_A, d_B, d_C, 2, 3, 2);
    download(C, d_C, 4);

    ASSERT_NEAR(C[0],  58.0f, EPS, "C[0,0] == 58");
    ASSERT_NEAR(C[1],  64.0f, EPS, "C[0,1] == 64");
    ASSERT_NEAR(C[2], 139.0f, EPS, "C[1,0] == 139");
    ASSERT_NEAR(C[3], 154.0f, EPS, "C[1,1] == 154");

    cuda_free(d_A); cuda_free(d_B); cuda_free(d_C);
}

static void test_matmul_transA(void) {
    printf("\n--- test_matmul_transA ---\n");
    // A stored as (K x M) = (2x2): [1 3]   -> A^T = [1 2]
    //                                [2 4]            [3 4]
    // B = (K x N) = (2x2): [5 6]
    //                       [7 8]
    // C = A^T * B (M=2,K=2,N=2) = [1*5+2*7  1*6+2*8] = [19 22]
    //                               [3*5+4*7  3*6+4*8]   [43 50]
    float A[] = {1, 3, 2, 4};
    float B[] = {5, 6, 7, 8};
    float C[4];

    float *d_A = cuda_malloc_float(4), *d_B = cuda_malloc_float(4), *d_C = cuda_malloc_float(4);
    upload(d_A, A, 4); upload(d_B, B, 4);

    cuda_matmul_transA(d_A, d_B, d_C, 2, 2, 2);
    download(C, d_C, 4);

    ASSERT_NEAR(C[0], 19.0f, EPS, "A^T*B [0,0] == 19");
    ASSERT_NEAR(C[1], 22.0f, EPS, "A^T*B [0,1] == 22");
    ASSERT_NEAR(C[2], 43.0f, EPS, "A^T*B [1,0] == 43");
    ASSERT_NEAR(C[3], 50.0f, EPS, "A^T*B [1,1] == 50");

    cuda_free(d_A); cuda_free(d_B); cuda_free(d_C);
}

static void test_matmul_transB(void) {
    printf("\n--- test_matmul_transB ---\n");
    // A = (M x K) = (2x2): [1 2]
    //                       [3 4]
    // B stored as (N x K) = (2x2): [5 7]   -> B^T = [5 6]
    //                                [6 8]            [7 8]
    // C = A * B^T (M=2,K=2,N=2) = [1*5+2*7  1*6+2*8] = [19 22]
    //                               [3*5+4*7  3*6+4*8]   [43 50]
    float A[] = {1, 2, 3, 4};
    float B[] = {5, 7, 6, 8};
    float C[4];

    float *d_A = cuda_malloc_float(4), *d_B = cuda_malloc_float(4), *d_C = cuda_malloc_float(4);
    upload(d_A, A, 4); upload(d_B, B, 4);

    cuda_matmul_transB(d_A, d_B, d_C, 2, 2, 2);
    download(C, d_C, 4);

    ASSERT_NEAR(C[0], 19.0f, EPS, "A*B^T [0,0] == 19");
    ASSERT_NEAR(C[1], 22.0f, EPS, "A*B^T [0,1] == 22");
    ASSERT_NEAR(C[2], 43.0f, EPS, "A*B^T [1,0] == 43");
    ASSERT_NEAR(C[3], 50.0f, EPS, "A*B^T [1,1] == 50");

    cuda_free(d_A); cuda_free(d_B); cuda_free(d_C);
}

/* ================================================================== */
/*  BATCHNORM TESTS                                                   */
/* ================================================================== */
/* Layout: data is (features x batch_size), feature-major.            */

static void test_batchnorm_forward_zero_mean_unit_var(void) {
    printf("\n--- test_batchnorm_forward_zero_mean_unit_var ---\n");
    // 1 feature, batch of 3: values [1, 4, 7]
    // mean = 4, var = 6, std = sqrt(6 + eps)
    // gamma=1, beta=0 -> output is just x_hat (normalized)
    int features = 1, batch = 3;
    float in[]    = {1.0f, 4.0f, 7.0f};
    float gamma[] = {1.0f};
    float beta[]  = {0.0f};
    float out[3], mean[1], var[1];
    float eps = 1e-5f;

    float *d_in = cuda_malloc_float(3), *d_out = cuda_malloc_float(3);
    float *d_g  = cuda_malloc_float(1), *d_b   = cuda_malloc_float(1);
    float *d_m  = cuda_malloc_float(1), *d_v   = cuda_malloc_float(1);
    upload(d_in, in, 3); upload(d_g, gamma, 1); upload(d_b, beta, 1);

    cuda_batchnorm_forward(d_in, d_out, d_g, d_b, d_m, d_v, features, batch, eps);
    download(out, d_out, 3);
    download(mean, d_m, 1);
    download(var, d_v, 1);

    ASSERT_NEAR(mean[0], 4.0f, EPS, "mean == 4.0");
    ASSERT_NEAR(var[0],  6.0f, EPS, "var == 6.0");

    float inv_std = 1.0f / sqrtf(6.0f + eps);
    ASSERT_NEAR(out[0], (1.0f - 4.0f) * inv_std, EPS, "x_hat[0] normalized");
    ASSERT_NEAR(out[1], (4.0f - 4.0f) * inv_std, EPS, "x_hat[1] ~= 0 (at mean)");
    ASSERT_NEAR(out[2], (7.0f - 4.0f) * inv_std, EPS, "x_hat[2] normalized");

    cuda_free(d_in); cuda_free(d_out); cuda_free(d_g);
    cuda_free(d_b);  cuda_free(d_m);   cuda_free(d_v);
}

static void test_batchnorm_forward_with_scale_shift(void) {
    printf("\n--- test_batchnorm_forward_with_scale_shift ---\n");
    // 1 feature, batch of 2: [2, 4], mean=3, var=1
    // gamma=2, beta=5 -> y = 2*x_hat + 5
    int features = 1, batch = 2;
    float in[]    = {2.0f, 4.0f};
    float gamma[] = {2.0f};
    float beta[]  = {5.0f};
    float out[2], mean[1], var[1];
    float eps = 1e-5f;

    float *d_in = cuda_malloc_float(2), *d_out = cuda_malloc_float(2);
    float *d_g  = cuda_malloc_float(1), *d_b   = cuda_malloc_float(1);
    float *d_m  = cuda_malloc_float(1), *d_v   = cuda_malloc_float(1);
    upload(d_in, in, 2); upload(d_g, gamma, 1); upload(d_b, beta, 1);

    cuda_batchnorm_forward(d_in, d_out, d_g, d_b, d_m, d_v, features, batch, eps);
    download(out, d_out, 2);
    download(mean, d_m, 1);
    download(var, d_v, 1);

    float inv_std = 1.0f / sqrtf(1.0f + eps);
    float expected_0 = 2.0f * (2.0f - 3.0f) * inv_std + 5.0f;
    float expected_1 = 2.0f * (4.0f - 3.0f) * inv_std + 5.0f;

    ASSERT_NEAR(mean[0], 3.0f, EPS, "mean == 3.0");
    ASSERT_NEAR(var[0],  1.0f, EPS, "var == 1.0");
    ASSERT_NEAR(out[0], expected_0, EPS, "y[0] = gamma*x_hat + beta");
    ASSERT_NEAR(out[1], expected_1, EPS, "y[1] = gamma*x_hat + beta");

    cuda_free(d_in); cuda_free(d_out); cuda_free(d_g);
    cuda_free(d_b);  cuda_free(d_m);   cuda_free(d_v);
}

static void test_batchnorm_backward_dgamma_dbeta(void) {
    printf("\n--- test_batchnorm_backward_dgamma_dbeta ---\n");
    // 1 feature, batch of 2: in=[2, 4], mean=3, var=1
    // dout = [1, 1]
    // dbeta = sum(dout) = 2
    // dgamma = sum(dout * x_hat)
    int features = 1, batch = 2;
    float in[]    = {2.0f, 4.0f};
    float dout_h[]= {1.0f, 1.0f};
    float gamma[] = {1.0f};
    float mean_h[]= {3.0f};
    float var_h[] = {1.0f};
    float eps = 1e-5f;

    float din[2], dgamma[1], dbeta[1];

    float *d_dout = cuda_malloc_float(2), *d_in = cuda_malloc_float(2);
    float *d_m = cuda_malloc_float(1), *d_v = cuda_malloc_float(1), *d_g = cuda_malloc_float(1);
    float *d_din = cuda_malloc_float(2), *d_dg = cuda_malloc_float(1), *d_db = cuda_malloc_float(1);

    upload(d_dout, dout_h, 2); upload(d_in, in, 2);
    upload(d_m, mean_h, 1);    upload(d_v, var_h, 1);
    upload(d_g, gamma, 1);

    cuda_batchnorm_backward(d_dout, d_in, d_m, d_v, d_g, d_din, d_dg, d_db, features, batch, eps);
    download(dgamma, d_dg, 1);
    download(dbeta, d_db, 1);

    float inv_std = 1.0f / sqrtf(1.0f + eps);
    float x_hat_0 = (2.0f - 3.0f) * inv_std;
    float x_hat_1 = (4.0f - 3.0f) * inv_std;
    float expected_dgamma = x_hat_0 + x_hat_1;

    ASSERT_NEAR(dbeta[0],  2.0f,            EPS, "dbeta = sum(dout) == 2");
    ASSERT_NEAR(dgamma[0], expected_dgamma, EPS, "dgamma = sum(dout * x_hat)");

    cuda_free(d_dout); cuda_free(d_in); cuda_free(d_m);
    cuda_free(d_v); cuda_free(d_g); cuda_free(d_din);
    cuda_free(d_dg); cuda_free(d_db);
}

/* ================================================================== */
/*  CONV2D (im2col / col2im) TESTS                                   */
/* ================================================================== */

static void test_im2col_1x1_kernel_is_identity(void) {
    printf("\n--- test_im2col_1x1_kernel_is_identity ---\n");
    // 1 channel, 2x2 image, 1x1 kernel, stride=1, pad=0
    // im2col with 1x1 kernel should just copy the input
    float in[] = {1.0f, 2.0f, 3.0f, 4.0f};
    int C_in = 1, H = 2, W = 2, kH = 1, kW = 1, stride = 1, pad = 0;
    int out_H = 2, out_W = 2;
    int col_size = C_in * kH * kW * out_H * out_W;  // 4
    float col[4];

    float *d_in = cuda_malloc_float(4), *d_col = cuda_malloc_float(col_size);
    upload(d_in, in, 4);

    cuda_im2col(d_in, C_in, H, W, kH, kW, stride, pad, d_col);
    download(col, d_col, col_size);

    ASSERT_NEAR(col[0], 1.0f, EPS, "im2col 1x1: [0] == 1");
    ASSERT_NEAR(col[1], 2.0f, EPS, "im2col 1x1: [1] == 2");
    ASSERT_NEAR(col[2], 3.0f, EPS, "im2col 1x1: [2] == 3");
    ASSERT_NEAR(col[3], 4.0f, EPS, "im2col 1x1: [3] == 4");

    cuda_free(d_in); cuda_free(d_col);
}

static void test_im2col_3x3_with_padding(void) {
    printf("\n--- test_im2col_3x3_with_padding ---\n");
    // 1 channel, 3x3 image, 3x3 kernel, stride=1, pad=1 -> out 3x3
    // just verify the center patch (oh=1,ow=1) which covers the full image
    float in[] = {1, 2, 3,
                  4, 5, 6,
                  7, 8, 9};
    int C_in = 1, H = 3, W = 3, kH = 3, kW = 3, stride = 1, pad = 1;
    int out_H = 3, out_W = 3;
    int col_size = C_in * kH * kW * out_H * out_W;  // 81
    float* col = (float*)malloc(col_size * sizeof(float));

    float *d_in = cuda_malloc_float(9), *d_col = cuda_malloc_float(col_size);
    upload(d_in, in, 9);

    cuda_im2col(d_in, C_in, H, W, kH, kW, stride, pad, d_col);
    download(col, d_col, col_size);

    // center output pixel (oh=1, ow=1) should see the full 3x3 image
    // col layout: for each (c, kh, kw) we have out_H*out_W values
    // pixel (oh=1,ow=1) index within each kernel position = 1*out_W + 1 = 4
    // position (c=0,kh=0,kw=0): index 0*9 + 4 = 4
    // position (c=0,kh=1,kw=1): index 4*9 + 4 = 40   -> center of kernel = center of image = 5
    ASSERT_NEAR(col[4*9 + 4], 5.0f, EPS, "center patch, center pixel == 5 (image center)");

    // top-left corner of center patch: (c=0,kh=0,kw=0) at (oh=1,ow=1)
    // maps to in[0*3+0] = 1
    ASSERT_NEAR(col[0*9 + 4], 1.0f, EPS, "center patch, top-left == 1");

    free(col);
    cuda_free(d_in); cuda_free(d_col);
}

static void test_col2im_reverses_im2col(void) {
    printf("\n--- test_col2im_reverses_im2col ---\n");
    // 1 channel, 2x2 image, 1x1 kernel, stride=1, pad=0
    // im2col then col2im should recover the original
    float in[] = {10.0f, 20.0f, 30.0f, 40.0f};
    int C_in = 1, H = 2, W = 2, kH = 1, kW = 1, stride = 1, pad = 0;
    int col_size = 4;
    float recovered[4];

    float *d_in = cuda_malloc_float(4), *d_col = cuda_malloc_float(col_size), *d_rec = cuda_malloc_float(4);
    upload(d_in, in, 4);

    cuda_im2col(d_in, C_in, H, W, kH, kW, stride, pad, d_col);

    cuda_memset_zero(d_rec, 4);
    cuda_col2im(d_col, C_in, H, W, kH, kW, stride, pad, d_rec);
    download(recovered, d_rec, 4);

    ASSERT_NEAR(recovered[0], 10.0f, EPS, "col2im recovers [0] == 10");
    ASSERT_NEAR(recovered[1], 20.0f, EPS, "col2im recovers [1] == 20");
    ASSERT_NEAR(recovered[2], 30.0f, EPS, "col2im recovers [2] == 30");
    ASSERT_NEAR(recovered[3], 40.0f, EPS, "col2im recovers [3] == 40");

    cuda_free(d_in); cuda_free(d_col); cuda_free(d_rec);
}

/* ================================================================== */

int main(void) {
    printf("========== CUDA KERNEL UNIT TESTS ==========\n");

    cuda_backend_init();

    /* elementwise */
    test_add();
    test_sub();
    test_mul();
    test_scale();

    /* activations forward */
    test_relu_forward();
    test_sigmoid_forward();
    test_tanh_forward();

    /* activations backward */
    test_relu_backward();
    test_sigmoid_backward();
    test_tanh_backward();
    test_sigmoid_backward_scales_by_dA();

    /* reduce */
    test_sum_rows();
    test_sum_cols();
    test_sum_rows_single_row();

    /* matmul */
    test_matmul_identity();
    test_matmul_2x3_times_3x2();
    test_matmul_transA();
    test_matmul_transB();

    /* batchnorm */
    test_batchnorm_forward_zero_mean_unit_var();
    test_batchnorm_forward_with_scale_shift();
    test_batchnorm_backward_dgamma_dbeta();

    /* conv2d */
    test_im2col_1x1_kernel_is_identity();
    test_im2col_3x3_with_padding();
    test_col2im_reverses_im2col();

    printf("\n============================================\n");
    printf("Results: %d passed, %d failed\n", g_passed, g_failed);
    printf("============================================\n");

    cuda_backend_cleanup();
    return g_failed > 0 ? 1 : 0;
}
