//tests were automatically generated by claude hahaha
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <cuda_runtime.h>
#include <cublas_v2.h>
#include "../cuda/cuda_backend.h"
#include "../cuda/cuda_mem.h"

/* ------------------------------------------------------------------ */
/*  Minimal test harness                                              */
/* ------------------------------------------------------------------ */

static int g_passed = 0;
static int g_failed = 0;

#define ASSERT_TRUE(expr, msg)                                         \
    do {                                                               \
        if (expr) { printf("  [PASS] %s\n", msg); g_passed++; }       \
        else      { printf("  [FAIL] %s\n", msg); g_failed++; }       \
    } while (0)

#define ASSERT_EQ_FLOAT(actual, expected, msg)                         \
    do {                                                               \
        if ((actual) == (expected)) {                                  \
            printf("  [PASS] %s\n", msg);                              \
            g_passed++;                                                \
        } else {                                                       \
            printf("  [FAIL] %s  (expected %.4f, got %.4f)\n",         \
                   msg, (double)(expected), (double)(actual));          \
            g_failed++;                                                \
        }                                                              \
    } while (0)

#define ASSERT_NOT_NULL(ptr, msg)                                      \
    do {                                                               \
        if ((ptr) != NULL) { printf("  [PASS] %s\n", msg); g_passed++; } \
        else               { printf("  [FAIL] %s\n", msg); g_failed++; } \
    } while (0)

#define ASSERT_NULL(ptr, msg)                                          \
    do {                                                               \
        if ((ptr) == NULL) { printf("  [PASS] %s\n", msg); g_passed++; } \
        else               { printf("  [FAIL] %s\n", msg); g_failed++; } \
    } while (0)

/* ------------------------------------------------------------------ */
/*  Tests: backend lifecycle                                          */
/* ------------------------------------------------------------------ */

static void test_backend_init_creates_handle(void) {
    printf("\n--- test_backend_init_creates_handle ---\n");
    cuda_backend_init();

    cublasHandle_t handle = cuda_backend_get_handle();
    ASSERT_NOT_NULL(handle, "handle is non-NULL after init");
}

static void test_backend_cleanup_nulls_handle(void) {
    printf("\n--- test_backend_cleanup_nulls_handle ---\n");
    cuda_backend_cleanup();

    cublasHandle_t handle = cuda_backend_get_handle();
    ASSERT_NULL(handle, "handle is NULL after cleanup");

    cuda_backend_init();
}

/* ------------------------------------------------------------------ */
/*  Tests: cuda_malloc_float / cuda_free                              */
/* ------------------------------------------------------------------ */

static void test_malloc_returns_valid_pointer(void) {
    printf("\n--- test_malloc_returns_valid_pointer ---\n");

    float* d_ptr = cuda_malloc_float(512);
    ASSERT_NOT_NULL(d_ptr, "cuda_malloc_float(512) returns non-NULL");
    cuda_free(d_ptr);
}

static void test_free_null_is_safe(void) {
    printf("\n--- test_free_null_is_safe ---\n");

    cuda_free(NULL);
    ASSERT_TRUE(1, "cuda_free(NULL) does not crash");
}

/* ------------------------------------------------------------------ */
/*  Tests: host <-> device copy                                       */
/* ------------------------------------------------------------------ */

static void test_copy_roundtrip_preserves_values(void) {
    printf("\n--- test_copy_roundtrip_preserves_values ---\n");

    float src[] = {1.0f, -2.5f, 3.14f, 0.0f, 99.9f};
    int n = 5;
    float dst[5] = {0};

    float* d_buf = cuda_malloc_float(n);
    cuda_copy_to_device(d_buf, src, n);
    cuda_copy_to_host(dst, d_buf, n);
    cuda_free(d_buf);

    ASSERT_EQ_FLOAT(dst[0],  1.0f,  "element 0 == 1.0");
    ASSERT_EQ_FLOAT(dst[1], -2.5f,  "element 1 == -2.5");
    ASSERT_EQ_FLOAT(dst[2],  3.14f, "element 2 == 3.14");
    ASSERT_EQ_FLOAT(dst[3],  0.0f,  "element 3 == 0.0");
    ASSERT_EQ_FLOAT(dst[4], 99.9f,  "element 4 == 99.9");
}

static void test_copy_single_element(void) {
    printf("\n--- test_copy_single_element ---\n");

    float src = 42.0f;
    float dst = 0.0f;

    float* d_buf = cuda_malloc_float(1);
    cuda_copy_to_device(d_buf, &src, 1);
    cuda_copy_to_host(&dst, d_buf, 1);
    cuda_free(d_buf);

    ASSERT_EQ_FLOAT(dst, 42.0f, "single element roundtrip == 42.0");
}

/* ------------------------------------------------------------------ */
/*  Tests: cuda_memset_zero                                           */
/* ------------------------------------------------------------------ */

static void test_memset_zero_clears_all(void) {
    printf("\n--- test_memset_zero_clears_all ---\n");

    float src[] = {5.0f, 10.0f, 15.0f, 20.0f};
    int n = 4;
    float dst[4];

    float* d_buf = cuda_malloc_float(n);
    cuda_copy_to_device(d_buf, src, n);
    cuda_memset_zero(d_buf, n);
    cuda_copy_to_host(dst, d_buf, n);
    cuda_free(d_buf);

    ASSERT_EQ_FLOAT(dst[0], 0.0f, "element 0 == 0.0 after memset");
    ASSERT_EQ_FLOAT(dst[1], 0.0f, "element 1 == 0.0 after memset");
    ASSERT_EQ_FLOAT(dst[2], 0.0f, "element 2 == 0.0 after memset");
    ASSERT_EQ_FLOAT(dst[3], 0.0f, "element 3 == 0.0 after memset");
}

static void test_memset_zero_partial(void) {
    printf("\n--- test_memset_zero_partial ---\n");

    float src[] = {1.0f, 2.0f, 3.0f, 4.0f};
    float dst[4];

    float* d_buf = cuda_malloc_float(4);
    cuda_copy_to_device(d_buf, src, 4);

    cuda_memset_zero(d_buf, 2);

    cuda_copy_to_host(dst, d_buf, 4);
    cuda_free(d_buf);

    ASSERT_EQ_FLOAT(dst[0], 0.0f, "first 2 zeroed: element 0 == 0.0");
    ASSERT_EQ_FLOAT(dst[1], 0.0f, "first 2 zeroed: element 1 == 0.0");
    ASSERT_EQ_FLOAT(dst[2], 3.0f, "untouched: element 2 == 3.0");
    ASSERT_EQ_FLOAT(dst[3], 4.0f, "untouched: element 3 == 4.0");
}

/* ------------------------------------------------------------------ */
/*  Tests: large buffer                                               */
/* ------------------------------------------------------------------ */

static void test_large_buffer_roundtrip(void) {
    printf("\n--- test_large_buffer_roundtrip ---\n");

    int n = 1 << 16;  // 65536 floats
    float* src = (float*)malloc(n * sizeof(float));
    float* dst = (float*)malloc(n * sizeof(float));
    for (int i = 0; i < n; i++) src[i] = (float)i;

    float* d_buf = cuda_malloc_float(n);
    cuda_copy_to_device(d_buf, src, n);
    cuda_copy_to_host(dst, d_buf, n);
    cuda_free(d_buf);

    ASSERT_EQ_FLOAT(dst[0],     0.0f,     "large buf: first element");
    ASSERT_EQ_FLOAT(dst[1000],  1000.0f,  "large buf: element 1000");
    ASSERT_EQ_FLOAT(dst[n - 1], (float)(n - 1), "large buf: last element");

    free(src);
    free(dst);
}

/* ------------------------------------------------------------------ */

int main(void) {
    printf("========== CUDA CORE UNIT TESTS ==========\n");

    test_backend_init_creates_handle();
    test_backend_cleanup_nulls_handle();

    test_malloc_returns_valid_pointer();
    test_free_null_is_safe();

    test_copy_roundtrip_preserves_values();
    test_copy_single_element();

    test_memset_zero_clears_all();
    test_memset_zero_partial();

    test_large_buffer_roundtrip();

    printf("\n==========================================\n");
    printf("Results: %d passed, %d failed\n", g_passed, g_failed);
    printf("==========================================\n");

    cuda_backend_cleanup();
    return g_failed > 0 ? 1 : 0;
}
